baseurl = "http://a4p-website-aubort.c9users.io/"
languageCode = "en-us"
title = "A4P - All for Projects"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"



[params]
    author = "pascal aubort"
    primaryColor = "mdl-color--blue-grey-900"
    # Enter your tracking code to enable Google Analytics
    googleAnalytics = ""
    
    [params.navigation]
        categories = ['About us', 'Clients & Partners', 'References', 'Contacts']

    [params.content.about]
        title = 'About us'
        content = "A4P.ch GmbH steht für Projektmanagement im Data Center Bereich für Kommerzielle und Non Profit Organisationen (NPO).Das riesige Angebot von Data Center Lösungen stellt ausserordentliche Anforderungen an die Betreiber und der Projektorganisation.  Wir bieten unseren Kunden die flexible Projektorganisation (PMO) mit eigenenwickelten Mitteln und Tools zur effektiven Erreichung Ihrer Ziele. Auf Grund Jahrzehnte Erfahrung im Bereich Data Center sind wir Ihr Partner für Ihr nächstes Projekt. "
    
    [params.content.casestudies]
        title = 'References'
        content = "asd"
        
    