baseurl = "http://aubort.github.io/a4p-website"
languageCode = "en-us"
title = "A4P - All for Projects"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
    author = "pascal aubort"
    primaryColor = "mdl-color--blue-grey-900"

    [params.navigation]
        categories = ['About', 'Partners', 'Case Studies', 'Contact us']
        