baseurl = "http://a4p-website-aubort.c9users.io/"
languageCode = "en-us"
title = "A4P - All for Projects"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
    author = "pascal aubort"
    primaryColor = "mdl-color--blue-grey-900"

    [params.navigation]
        categories = ['Ueber uns', 'Partners', 'Case Studies', 'Contact us']

    [params.content.about]
        title = 'Über uns'
        content = "A4P.ch GmbH steht für Projektmanagement im Data Center Bereich für Kommerzielle und Non Profit Organisationen (NPO).Das riesige Angebot von Data Center Lösungen stellt ausserordentliche Anforderungen an die Betreiber und der Projektorganisation.  Wir bieten unseren Kunden die flexible Projektorganisation (PMO) mit eigenenwickelten Mitteln und Tools zur effektiven Erreichung Ihrer Ziele. Auf Grund Jahrzehnte Erfahrung im Bereich Data Center sind wir Ihr Partner für Ihr nächstes Projekt. "
    
    [params.content.casestudies]
        title = 'Case Studies'
        content = "asd"
        
    